name = "worker-apollo-server"
main = "build/index.js"

workers_dev = true
kv_namespaces = [
  { binding = "GRAPHQL_CACHE", id = "dbdc624f2c684f1bb88fa38ab249a13e" }
]

compatibility_date = "2022-09-29"

[build]
command = "npm run generate && npm run build"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_PLAYGROUND_ENDPOINT = "/playground"
GRAPHQL_KV_CACHE = "true"
